version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...   
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 151500355301.dkr.ecr.ap-south-1.amazonaws.com/assignment:latest
      - docker push 151500355301.dkr.ecr.ap-south-1.amazonaws.com/assignment:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s:latest"}]' nodeapp 151500355301.dkr.ecr.ap-south-1.amazonaws.com/assignment > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
