version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...   
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 151500355301.dkr.ecr.ap-south-1.amazonaws.com/assignment:latest
      - docker push 151500355301.dkr.ecr.ap-south-1.amazonaws.com/assignment:latest
      - echo Pushing the Docker images...
      - apt-get update && apt-get install sshpass     
      - sshpass -p $SSHPASS ssh -o StrictHostKeyChecking=no deployuser@$EC2_IP "./deploy.sh > ./deploy.log" 
  post_build:
    commands:
      - echo Build completed and Deployment completed on `date`
